site_name: OWASP Projects
site_description: OWASP Project reference list
site_author: 'Enrico Branca, Johanna Curiel'
copyright: Content is available under a Creative Commons 3.0 (CC BY-SA 3.0) License unless otherwise noted.
#google_analytics: ['UA-4531126-1', 'owasp.org']

docs_dir: 'projects'
site_dir: 'html'
site_url: 'https://www.owasp.org/'
repo_url: 'https://github.com/OWASP'
dev_addr: '0.0.0.0:8000'

#theme_dir: 'custom_theme_cinder'
theme: readthedocs
# --->  Supported themes  <---
# mkdocs
# readthedocs
# --->  Deprecated themes !!  <---
# amelia
# bootstrap
# cerulean
# cosmo
# cyborg
# flatly
# journal
# readable
# simplex
# slate
# spacelab
# united
# yeti

use_directory_urls: false
site_favicon: 'favicons/OWASP_favicon.ico'
extra_css: []
extra_javascript: []
strict: true
markdown_extensions:
  - smarty
  - nl2br
  - toc:
      permalink: True
      separator: "_"
      anchorlink: False
  - sane_lists
  - fenced_code
  - codehilite
  - admonition
  - attr_list
  - def_list
  - abbr
  - tables
  - meta

pages:
- 'Home': 'index.md'

- 'Projects':
  - 'New Projects': 'lists/new_project.md'
  - 'Project Maturity': 'lists/maturity.md'
  - 'Project Classes': 'lists/classes.md'
  - 'Project Categories': 'lists/category.md'
  - 'Project Status': 'lists/status.md'

- 'Reviews':
  - 'Review Process': 'lists/review_process.md'
  - 'Review List':  'lists/review_list.md'
  - 'Reviewers':  'lists/reviewers.md'

- 'Individual Reviews (A to Z)':
  - 'AJAX Crawling Tool': 'review/ajax_crawling.md'
  - 'AppSensor': 'review/appsensor.md'
  - 'ASIDE': 'review/aside.md'
  - 'ASVS Assessment tool': 'review/asvs_assessment.md'
  - 'Broken Web Applications': 'review/broken_web_applications.md'
  - 'Bricks': 'review/bricks.md'
  - 'Bywaf': 'review/bywaf.md'
  - 'Click Me': 'review/click_me.md'
  - 'CSRFGuard': 'review/csrfguard.md'
  - 'Dependency Check': 'review/dependency_check.md'
  - 'Development Guide': 'review/development_guide.md'
  - 'Droid 10': 'review/droid_10.md'
  - 'EnDe': 'review/ende.md'
  - 'Esapi Ruby': 'review/esapi_ruby.md'
  - 'Faux Bank': 'review/faux_bank.md'
  - 'GoatDroid': 'review/goatdroid.md'
  - 'Hardened Phalcon': 'review/hardened_phalcon.md'
  - 'Hatkit Datafiddler': 'review/hatkit_datafiddler.md'
  - 'Hatkit Proxy': 'review/hatkit_proxy.md'
  - 'Java HTML Sanitizer': 'review/java_html_sanitizer.md'
  - 'KALP Mobile': 'review/kalp_mobile.md'
  - 'ModSecurity Core Rule Set (CRS)': 'review/modsecurity_core_rule_set.md'
  - 'Mutillidae II': 'review/mutillidae_2.md'
  - 'NINJA PingU': 'review/ninja_pingu.md'
  - 'O-Saft': 'review/o_saft.md'
  - 'Odz MultiCMSScanner': 'review/odz_multicmsscanner.md'
  - 'OWTF': 'review/owtf.md'
  - 'Passfault': 'review/passfault.md'
  - 'Path Traverser': 'review/path_traverser.md'
  - 'PCI Toolkit': 'review/pci_toolkit.md'
  - 'PHPRBAC': 'review/phprbac.md'
  - 'PHP Security': 'review/php_security.md'
  - 'Proxy': 'review/proxy.md'
  - 'Pygoat': 'review/pygoat.md'
  - 'Rails Goat': 'review/rails_goat.md'
  - 'SafeNuGet': 'review/safenuget.md'
  - 'Secure the Flag Competition': 'review/stfc.md'
  - 'Security Logging': 'review/security_logging.md'
  - 'SeraphimDroid': 'review/seraphimdroid.md'
  - 'Software Assurance Maturity Model (SAMM)': 'review/samm.md'
  - 'STeBB': 'review/stebb.md'
  - 'Vulnerable Web Applications Directory': 'review/vulnerable_web_applications_directory.md'
  - 'Wapiti': 'review/wapiti.md'
  - 'WASC Distributed Web Honeypots': 'review/wasc_dwh.md'
  - 'Web Testing Environment': 'review/web_testing_environment.md'
  - 'WEBGOAT': 'review/webgoat.md'
  - 'WhatTheFuzz': 'review/whatthefuzz.md'
  - 'Xenotix XSS Exploit Framework': 'review/xenotix.md'
  - 'ZAP': 'review/zap.md'
  - 'ZSC Tool': 'review/zsc_tool.md'


- Licenses:
  - 'Apache 2.0': 'license/apache-license-2.0.md'
  - 'CC BY-SA 3.0': 'license/CC_by-sa_3.0.md'
  - 'GPL v3.0': 'license/gpl_v3.md'
  - 'LGPL v3.0': 'license/lgpl_v3.md'
